### ISSUE TITLE
USER STORY: Expiry date for poll

### ISSUE THREAD

**Issue by Cal009** [Cal009/My-First-Agile-Project#5]
In order to automatically hide the poll as an administrator, I can pick the expiry date when publishing the poll

# Acceptance Criteria

- Acceptance Criteria 1: Poll should disappear at 23:59 on the final set day
- Acceptance Criteria 2: The poll should last for 3 days
- Acceptance Criteria 3: 

# Tasks

- [ ] Update the view: poll design to include the checkbox and to show the name of the submitter
- [ ] Create a new field in the model to track the username
- [ ] Test the functionality
